export const INDIAN_CITIES: { label: string; value: string }[] = [
  { label: 'Agartala', value: 'Agartala' },
  { label: 'Agra', value: 'Agra' },
  { label: 'Ahmedabad', value: 'Ahmedabad' },
  { label: 'Aizawl', value: 'Aizawl' },
  { label: 'Ajmer', value: 'Ajmer' },
  { label: 'Aligarh', value: 'Aligarh' },
  { label: 'Allahabad (Prayagraj)', value: 'Prayagraj' },
  { label: 'Ambala', value: 'Ambala' },
  { label: 'Amravati', value: 'Amravati' },
  { label: 'Amritsar', value: 'Amritsar' },
  { label: 'Anand', value: 'Anand' },
  { label: 'Aurangabad (Sambhajinagar)', value: 'Sambhajinagar' },
  { label: 'Bangalore (Bengaluru)', value: 'Bengaluru' },
  { label: 'Bareilly', value: 'Bareilly' },
  { label: 'Belgaum (Belagavi)', value: 'Belagavi' },
  { label: 'Bhilai', value: 'Bhilai' },
  { label: 'Bhopal', value: 'Bhopal' },
  { label: 'Bhubaneswar', value: 'Bhubaneswar' },
  { label: 'Bikaner', value: 'Bikaner' },
  { label: 'Bilaspur', value: 'Bilaspur' },
  { label: 'Chandigarh', value: 'Chandigarh' },
  { label: 'Chennai', value: 'Chennai' },
  { label: 'Coimbatore', value: 'Coimbatore' },
  { label: 'Cuttack', value: 'Cuttack' },
  { label: 'Dehradun', value: 'Dehradun' },
  { label: 'Delhi', value: 'Delhi' },
  { label: 'Dhanbad', value: 'Dhanbad' },
  { label: 'Dibrugarh', value: 'Dibrugarh' },
  { label: 'Durgapur', value: 'Durgapur' },
  { label: 'Erode', value: 'Erode' },
  { label: 'Faridabad', value: 'Faridabad' },
  { label: 'Gandhinagar', value: 'Gandhinagar' },
  { label: 'Gangtok', value: 'Gangtok' },
  { label: 'Ghaziabad', value: 'Ghaziabad' },
  { label: 'Gorakhpur', value: 'Gorakhpur' },
  { label: 'Guntur', value: 'Guntur' },
  { label: 'Gurugram', value: 'Gurugram' },
  { label: 'Guwahati', value: 'Guwahati' },
  { label: 'Gwalior', value: 'Gwalior' },
  { label: 'Hubli-Dharwad', value: 'Hubli-Dharwad' },
  { label: 'Hyderabad', value: 'Hyderabad' },
  { label: 'Imphal', value: 'Imphal' },
  { label: 'Indore', value: 'Indore' },
  { label: 'Itanagar', value: 'Itanagar' },
  { label: 'Jabalpur', value: 'Jabalpur' },
  { label: 'Jaipur', value: 'Jaipur' },
  { label: 'Jalandhar', value: 'Jalandhar' },
  { label: 'Jammu', value: 'Jammu' },
  { label: 'Jamshedpur', value: 'Jamshedpur' },
  { label: 'Jhansi', value: 'Jhansi' },
  { label: 'Jodhpur', value: 'Jodhpur' },
  { label: 'Kanpur', value: 'Kanpur' },
  { label: 'Kochi', value: 'Kochi' },
  { label: 'Kohima', value: 'Kohima' },
  { label: 'Kolhapur', value: 'Kolhapur' },
  { label: 'Kolkata', value: 'Kolkata' },
  { label: 'Kota', value: 'Kota' },
  { label: 'Kozhikode (Calicut)', value: 'Kozhikode' },
  { label: 'Lucknow', value: 'Lucknow' },
  { label: 'Ludhiana', value: 'Ludhiana' },
  { label: 'Madurai', value: 'Madurai' },
  { label: 'Mangalore (Mangaluru)', value: 'Mangaluru' },
  { label: 'Meerut', value: 'Meerut' },
  { label: 'Moradabad', value: 'Moradabad' },
  { label: 'Mumbai', value: 'Mumbai' },
  { label: 'Muzaffarpur', value: 'Muzaffarpur' },
  { label: 'Mysore (Mysuru)', value: 'Mysuru' },
  { label: 'Nagpur', value: 'Nagpur' },
  { label: 'Nashik', value: 'Nashik' },
  { label: 'Navi Mumbai', value: 'Navi Mumbai' },
  { label: 'Noida', value: 'Noida' },
  { label: 'Panaji', value: 'Panaji' },
  { label: 'Patna', value: 'Patna' },
  { label: 'Pondicherry (Puducherry)', value: 'Puducherry' },
  { label: 'Pune', value: 'Pune' },
  { label: 'Raipur', value: 'Raipur' },
  { label: 'Rajkot', value: 'Rajkot' },
  { label: 'Ranchi', value: 'Ranchi' },
  { label: 'Rourkela', value: 'Rourkela' },
  { label: 'Salem', value: 'Salem' },
  { label: 'Shillong', value: 'Shillong' },
  { label: 'Shimla', value: 'Shimla' },
  { label: 'Siliguri', value: 'Siliguri' },
  { label: 'Srinagar', value: 'Srinagar' },
  { label: 'Surat', value: 'Surat' },
  { label: 'Thane', value: 'Thane' },
  { label: 'Thiruvananthapuram', value: 'Thiruvananthapuram' },
  { label: 'Thrissur', value: 'Thrissur' },
  { label: 'Tiruchirappalli (Trichy)', value: 'Tiruchirappalli' },
  { label: 'Tirupati', value: 'Tirupati' },
  { label: 'Udaipur', value: 'Udaipur' },
  { label: 'Ujjain', value: 'Ujjain' },
  { label: 'Vadodara', value: 'Vadodara' },
  { label: 'Varanasi', value: 'Varanasi' },
  { label: 'Vijayawada', value: 'Vijayawada' },
  { label: 'Visakhapatnam', value: 'Visakhapatnam' },
  { label: 'Warangal', value: 'Warangal' },
];

