CREATE TABLE restaurant (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    name VARCHAR(200) NOT NULL,
    city VARCHAR(100) NOT NULL,
    food_type VARCHAR(50) NOT NULL,
    cuisine VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);